
services:
  db:
    image: postgres:16.3
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw
      POSTGRES_DB: The-System
    volumes:
     - postgres_data:/var/lib/postgresql/data
    ports:
     - "5432:5432"

  backend:
    image: zwray/reactcode-backend:0.1
    container_name: api
    depends_on:
      - db
    volumes:
      - ./fastapi:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:passw@db/The-System

  frontend:
    image: zwray/reactcode-frontend:1
    container_name: frontend
    ports:
     - "3000:5173"
    depends_on:
    - backend
    stdin_open: true
    tty: true

volumes: 
  postgres_data: